### ISSUE TITLE
Is the program abandoned?

### ISSUE THREAD

**Issue by mrkaban** [michaelsboost/kodeWeave#11]
Thank you very much for the free open source program!

Hello, thank you very much for a good program under a free open source license! Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA%D1%83/ide/kodeweave-%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0-%D0%BD%D0%B0-html-css-js.html).

Will stable releases be published here or SourceForge?

The project is interesting, so please don't abandon it!

**Comment by michaelsboost** [comment]
Спасибо и пожалуйста (my russian isn't the greatest, I'm still learning)

Aanyway to answer your question. All updates for this app and all my others will be here on Github. Also yes I have discontinued (or more/less abandonded) development of this app and all my others. This app along with all my others are just not a priority in my life at this time. 

I'm very happy with the free and open source work I've done. I've put the framework down for collaborative contributions so if anyone wants to add to it they're more than welcome (even encouraged) to do so.

**Comment by mrkaban** [comment]
Anyway, thanks for such a nice project! And for publishing it open source!

I, unfortunately, will not pull another project.
