### ISSUE TITLE
Preview Window Loads Nested Kodeweave App

### ISSUE THREAD

**Issue by JDWilliamson** [michaelsboost/kodeWeave#7]
On Mac OS Sierra when clicking on a simple button with a click event handler, the preview briefly updates to process the click action, but then a second app seems to load into the preview window. This happens every time I click the button without failure. I can refresh the top most level or enable auto-update to get back to the proper preview, but clicking the button again results in the same issue.

HTML:
~~~html
<!DOCTYPE html>
<html>
  <body>
    <form>
      <input type="text" id="myString">
      <output id="output"></output>
      <button id="myButton" onclick="someFunction(myString.value)">
        Make Uppercase
      </button>
    </form>
  </body>
</html>
~~~

JS:
~~~javascript
function someFunction(val)
{
  var output = document.getElementById("output");
  output.innerHTML = val;
}
~~~

No CSS.

I can nest it about four times before the preview is too small to find the input and buttons effectively.

The lowest nested window appears to be the active one with regards to the file menu bar, but I can still type in any of the windows. When typing in any of the windows none of them are in sync until refreshing a level at or above the edited window. It appears to only take the most recent window changes once refreshing.

Restarting the program does not appear to fix the issue.

![screen shot 2018-01-30 at 12 05 38 pm](https://user-images.githubusercontent.com/13559026/35582967-06efd5ac-05b6-11e8-9496-1172d520b286.png)
![screen shot 2018-01-30 at 12 06 35 pm](https://user-images.githubusercontent.com/13559026/35582974-091e6816-05b6-11e8-9f94-658570be848e.png)

**Comment by michaelsboost** [comment]
You're not using the [FORM](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form) tag properly.

> The **HTML <form>** element represents a document section that contains interactive controls to submit information to a web server.

Here are a few links that explain how to use the form tag properly.

- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form
- https://www.w3schools.com/js/js_validation.asp
- https://stackoverflow.com/questions/31066693/what-is-the-purpose-of-the-html-form-tag

Remember with kodeWeave we already add the Doctype for you. 
All you need to do is focus on the code in the body tag.

You just need to adjust your code a little bit and it'll work. 
https://www.michaelsboost.tk/kodeWeave/editor/#0c80c500cb50cffb98a729afeed4d55a

In your case all we need to do is remove the form tags as in this case they are not necessary.

```
<input type="text" id="myString">
<output id="output"></output>
<button id="myButton" onclick="someFunction(myString.value)">
  Make Uppercase
</button>
```
